### ISSUE TITLE
Tasks handler can only be used within its organisation

### ISSUE THREAD

**Issue by SmartLayer** [luisbustalu/Google-Spaces-Tasks-reporter#1]
I have this error, I guess it's because I use gsuite. can you add a note to README how to handle such?
![image](https://github.com/user-attachments/assets/2606f7d9-4151-4bc3-9c85-8403bcba019b)

**Comment by luisbustalu** [comment]
Hi @SmartLayer, the cause is not GSuite. When creating a new project in Google Cloud Console, you'll have it for internal use by default, unless you pass a certain requirements and verification process. However, you can add up to 100 mails to be whitelisted to use your application.

In this case, all you have to do is logging in to your Google Cloud Console and access **APIs & Services -> OAuth consent screen** page. Go to **Test users** section and add your own mail in there. After that, you should be able to access the application with the previously whitelisted account.

![imagen](https://github.com/user-attachments/assets/cf9cf1bf-74e9-4c13-b467-eaded8b07519)

For GSuite users, as your case, instead of seeing "Test users" you'll see something like "Authorized domains" where you can add external domains to access the application, instead of emails. I haven't tested that so far, but should work. The other option is to change the application status to testing status, then you'll be able to whitelist mails to access the application, as shown in the image above.
